ConvAvif: src/bind.cpp File Reference
bind.cpp File Reference
#include "encoder_config.h"
#include "error.h"
#include "imagebuffer.h"
#include "imageconverter.h"
#include "result.h"
#include <emscripten/bind.h>
Functions
EMSCRIPTEN_BINDINGS (ImageBuffer)
EMSCRIPTEN_BINDINGS (ImageConverter)
EMSCRIPTEN_BINDINGS (avif_enums)
EMSCRIPTEN_BINDINGS (ErrorHandling)
Function Documentation
EMSCRIPTEN_BINDINGS() [1/4]
EMSCRIPTEN_BINDINGS (avif_enums)
Definition at line 72 of file bind.cpp.
EMSCRIPTEN_BINDINGS() [2/4]
EMSCRIPTEN_BINDINGS (ErrorHandling)
Definition at line 86 of file bind.cpp.
References AVIF_ERROR_START, Error::code, CONVERSION_FAILED, ENCODER_CREATION_FAILED, ENCODING_FAILED, jsResult::getError(), jsResult::getImage(), jsResult::hasError(), jsResult::hasImage(), IMAGE_LOAD_FAILED, INVALID_ARGUMENT, INVALID_DIMENSIONS, INVALID_QUANTIZER_VALUES, Error::message, OK, OUT_OF_MEMORY, Error::stackTrace, and UNKNOWN_ERROR.
EMSCRIPTEN_BINDINGS() [3/4]
EMSCRIPTEN_BINDINGS (ImageBuffer)
Definition at line 8 of file bind.cpp.
References ImageBuffer::getData(), ImageBuffer::getRawData(), and ImageBuffer::getSize().
EMSCRIPTEN_BINDINGS() [4/4]
EMSCRIPTEN_BINDINGS (ImageConverter)
Definition at line 16 of file bind.cpp.
References AOM, AUTO, convertImageDirect(), Speed::default_speed, EncodeConfig::getCodecChoice(), Speed::getDefault(), EncodeConfig::getMaxQuantizer(), EncodeConfig::getMinQuantizer(), EncodeConfig::getPreset(), Speed::getPreset(), EncodeConfig::getQuality(), Speed::getRange(), EncodeConfig::getSpeed(), EncodeConfig::getTileColsLog2(), EncodeConfig::getTileRowsLog2(), Good, Speed::isValid(), SpeedRange::max, MemoryHungry, SpeedRange::min, EncodeConfig::pixelFormat, Speed::preset_, RealTime, Speed::set(), EncodeConfig::setCodecChoice(), EncodeConfig::setMaxQuantizer(), EncodeConfig::setMinQuantizer(), EncodeConfig::setPreset(), EncodeConfig::setQuality(), Speed::setSpeedRange(), EncodeConfig::setTileColsLog2(), EncodeConfig::setTileRowsLog2(), EncodeConfig::sharpness, SVT, EncodeConfig::tune, TUNE_DEFAULT, TUNE_PSNR, TUNE_SSIM, and EncodeConfig::updateSpeed().