ConvAvif: ImageGuru Class Reference
ImageGuru Class Reference
Utility class for image format detection and support checking.
#include <imageGuru.h>
Classes
struct imageSupport
Structure for tracking image format support status.
Static Public Member Functions
static ImageType GetImageType (const std::vector< uint8_t > &data)
Detect the image format from binary data.
static bool IsValid (const std::vector< uint8_t > &data)
Check if binary data appears to be a valid image.
static bool IsSpecificType (const std::vector< uint8_t > &data, ImageType type)
Check if binary data matches a specific image format.
static bool isSupported (const ImageType type)
Check if a specific image type is supported for conversion.
static std::string typeToString (const ImageType type)
Convert an ImageType enum to a string representation.
Static Private Attributes
static constexpr std::array< imageSupport, 8 > supported_image
Array defining which image formats are supported for conversion.
Detailed Description
Utility class for image format detection and support checking.
This class provides static methods to detect image formats from binary data and check whether specific formats are supported for conversion to AVIF.
Definition at line 31 of file imageGuru.h.
Member Function Documentation
GetImageType()
static ImageType ImageGuru::GetImageType (const std::vector< uint8_t > & data) inline static
Detect the image format from binary data.
Examines the file header/magic bytes in the provided data to determine the image format.
Parameters
data Binary image data to analyze
Returns
Detected ImageType, or ImageType::UNKNOWN if format isn't recognized
Definition at line 42 of file imageGuru.h.
References AVIF, BMP, GIF, JPEG, PNG, TIFF, UNKNOWN, and WEBP.
Referenced by convertImageDirect(), IsSpecificType(), and IsValid().
IsSpecificType()
static bool ImageGuru::IsSpecificType (const std::vector< uint8_t > & data, ImageType type) inline static
Check if binary data matches a specific image format.
Parameters
data Binary data to check
type Specific ImageType to check for
Returns
true if the data matches the specified format, false otherwise
Definition at line 121 of file imageGuru.h.
References GetImageType().
isSupported()
static bool ImageGuru::isSupported (const ImageType type) inline static
Check if a specific image type is supported for conversion.
Parameters
type The ImageType to check support for
Returns
true if the format is supported for conversion, false otherwise
Definition at line 139 of file imageGuru.h.
References supported_image.
Referenced by convertImageDirect().
IsValid()
static bool ImageGuru::IsValid (const std::vector< uint8_t > & data) inline static
Check if binary data appears to be a valid image.
Parameters
data Binary data to check
Returns
true if the data appears to be a recognized image format, false otherwise
Definition at line 110 of file imageGuru.h.
References GetImageType(), and UNKNOWN.
typeToString()
static std::string ImageGuru::typeToString (const ImageType type) inline static
Convert an ImageType enum to a string representation.
Parameters
type The ImageType to convert
Returns
String representation of the image type
Definition at line 154 of file imageGuru.h.
References AVIF, BMP, GIF, JPEG, PNG, TIFF, UNKNOWN, and WEBP.
Referenced by convertImageDirect().
Member Data Documentation
supported_image
std::array<imageSupport, 8> ImageGuru::supported_image static constexpr private
Initial value:
= {
      {{ImageType::JPEG, true},
       {ImageType::PNG, true},
       {ImageType::GIF, false},
       {ImageType::BMP, false},
       {ImageType::TIFF, false},
       {ImageType::WEBP, false},
       {ImageType::AVIF, true},
       {ImageType::UNKNOWN, false}}}
Array defining which image formats are supported for conversion.
This array maps each ImageType to a boolean indicating whether that format can be converted to AVIF by the library.
Definition at line 184 of file imageGuru.h.
Referenced by isSupported().
The documentation for this class was generated from the following file:
include/imageGuru.h