ConvAvif: src/error.cpp File Reference
error.cpp File Reference
#include "error.h"
Functions
ConverterError avifToConverterError (avifResult result)
Converts an AVIF library error code to a ConverterError.
std::string getErrorMessage (ConverterError error)
Get a human-readable error message for an error code.
emscripten::val toJsError (const Error &e)
Convert a C++ Error object to a JavaScript error object.
Function Documentation
avifToConverterError()
ConverterError avifToConverterError (avifResult result)
Converts an AVIF library error code to a ConverterError.
Maps the native AVIF library error codes to the application's error enum.
Parameters
result AVIF library result code
Returns
Equivalent ConverterError code
Definition at line 6 of file error.cpp.
References AVIF_ERROR_START.
Referenced by convert_image(), and SetAvifOption().
getErrorMessage()
std::string getErrorMessage (ConverterError error)
Get a human-readable error message for an error code.
Parameters
error Error code to get the message for
Returns
Standard error message for the given code
Definition at line 13 of file error.cpp.
References AVIF_ERROR_START, CONVERSION_FAILED, ENCODER_CREATION_FAILED, ENCODING_FAILED, IMAGE_LOAD_FAILED, INVALID_DIMENSIONS, INVALID_QUANTIZER_VALUES, OK, and OUT_OF_MEMORY.
toJsError()
emscripten::val toJsError (const Error & e)
Convert a C++ Error object to a JavaScript error object.
Creates a JavaScript error object with properties for code, message, and stackTrace suitable for returning to JavaScript code.
Parameters
e The C++ Error object to convert
Returns
JavaScript object representing the error
Definition at line 44 of file error.cpp.
References Error::code, Error::message, and Error::stackTrace.
Referenced by convertImageDirect().