ConvAvif: include/error.h File Reference
error.h File Reference
Error handling for AVIF conversion operations.
#include <avif/avif.h>
#include <emscripten/val.h>
#include <string>
Classes
class Error
Error class for reporting conversion errors.
Enumerations
enum class ConverterError {
OK = 0 , INVALID_DIMENSIONS = 100 , UNSUPPORTED_IMAGETYPE , IMAGE_LOAD_FAILED ,
ENCODER_CREATION_FAILED , CONVERSION_FAILED , ENCODING_FAILED , INVALID_ARGUMENT ,
OUT_OF_MEMORY , INVALID_QUANTIZER_VALUES , UNKNOWN_ERROR , AVIF_ERROR_START = 200
}
Error codes for the image converter.
Functions
ConverterError avifToConverterError (avifResult result)
Converts an AVIF library error code to a ConverterError.
std::string getErrorMessage (ConverterError error)
Get a human-readable error message for an error code.
emscripten::val toJsError (const Error &e)
Convert a C++ Error object to a JavaScript error object.
Detailed Description
Error handling for AVIF conversion operations.
Author
ConvAvif Developer
Date
2025
This file defines error types, error codes, and helper functions for handling and reporting errors during AVIF conversion operations.
Definition in file error.h.
Enumeration Type Documentation
ConverterError
enum class ConverterError strong
Error codes for the image converter.
These error codes identify different failure modes in the conversion process. Error codes 100-199 are specific to the converter, while codes 200+ are mapped from the AVIF library.
Enumerator
OK
No error, operation successful.
INVALID_DIMENSIONS
Image dimensions are invalid (too small/large)
UNSUPPORTED_IMAGETYPE
Image format is not supported.
IMAGE_LOAD_FAILED
Failed to load/decode the input image.
ENCODER_CREATION_FAILED
Failed to create the AVIF encoder.
CONVERSION_FAILED
Failed during the RGB to YUV conversion.
ENCODING_FAILED
Failed during the encoding process.
INVALID_ARGUMENT
Invalid argument provided to a function.
OUT_OF_MEMORY
Memory allocation failed.
INVALID_QUANTIZER_VALUES
Invalid quantizer values (e.g., min > max)
UNKNOWN_ERROR
Unspecified error.
AVIF_ERROR_START
Start of error codes mapped from avifResult.
Definition at line 24 of file error.h.
Function Documentation
avifToConverterError()
ConverterError avifToConverterError (avifResult result)
Converts an AVIF library error code to a ConverterError.
Maps the native AVIF library error codes to the application's error enum.
Parameters
result AVIF library result code
Returns
Equivalent ConverterError code
Definition at line 6 of file error.cpp.
References AVIF_ERROR_START.
Referenced by convert_image(), and SetAvifOption().
getErrorMessage()
std::string getErrorMessage (ConverterError error)
Get a human-readable error message for an error code.
Parameters
error Error code to get the message for
Returns
Standard error message for the given code
Definition at line 13 of file error.cpp.
References AVIF_ERROR_START, CONVERSION_FAILED, ENCODER_CREATION_FAILED, ENCODING_FAILED, IMAGE_LOAD_FAILED, INVALID_DIMENSIONS, INVALID_QUANTIZER_VALUES, OK, and OUT_OF_MEMORY.
toJsError()
emscripten::val toJsError (const Error & e)
Convert a C++ Error object to a JavaScript error object.
Creates a JavaScript error object with properties for code, message, and stackTrace suitable for returning to JavaScript code.
Parameters
e The C++ Error object to convert
Returns
JavaScript object representing the error
Definition at line 44 of file error.cpp.
References Error::code, Error::message, and Error::stackTrace.
Referenced by convertImageDirect().