ConvAvif: include/imageconverter.h File Reference
imageconverter.h File Reference
Header for image conversion functionality to AVIF format.
#include "avif_helper.h"
#include "constants.h"
#include "encoder_config.h"
#include "error.h"
#include "imageGuru.h"
#include "imagebuffer.h"
#include "result.h"
#include <algorithm>
#include <avif/avif.h>
#include <string>
Functions
Result convert_image (ImageType type, const std::vector< uint8_t > &input_data, int width, int height, const EncodeConfig &config)
Converts an image to AVIF format with specified parameters.
emscripten::val convertImageDirect (emscripten::val jsData, int width, int height, const EncodeConfig &config)
JavaScript binding wrapper for image conversion.
Detailed Description
Header for image conversion functionality to AVIF format.
Author
ConvAvif Developer
Date
2025
Provides functions to convert various image formats to AVIF using the AVIF library with configurable encoding parameters.
Definition in file imageconverter.h.
Function Documentation
convert_image()
Result convert_image (ImageType type, const std::vector< uint8_t > & input_data, int width, int height, const EncodeConfig & config)
Converts an image to AVIF format with specified parameters.
Parameters
type The type of input image (e.g., PNG, JPEG)
input_data Vector containing the raw image data
width Desired width of the output image (will resize if different from source)
height Desired height of the output image (will resize if different from source)
config Encoding configuration parameters
Returns
Result object containing either the encoded image data on success or an Error on failure
Note
Image dimensions are limited to 1-8192px
This function handles the complete conversion pipeline:
Validates input dimensions
Loads and decodes input image data
Resizes image if necessary
Configures the AVIF encoder based on provided settings
Converts RGB data to YUV colorspace
Encodes image to AVIF format
Parameters
type The type of input image (e.g., PNG, JPEG)
input_data Vector containing the raw image data
width Desired width of the output image
height Desired height of the output image
config Encoding configuration parameters
Returns
Result object containing either the encoded image data or an Error
Definition at line 47 of file imageconverter.cpp.
References AOM, avifToConverterError(), EncodeConfig::codecChoice, CONVERSION_FAILED, ENCODER_CREATION_FAILED, EncodeConfig::getSpeed(), IMAGE_LOAD_FAILED, INVALID_DIMENSIONS, INVALID_QUANTIZER_VALUES, MAX_QUANTIZER, EncodeConfig::maxQuantizer, EncodeConfig::minQuantizer, EncodeConfig::pixelFormat, EncodeConfig::printConfig(), EncodeConfig::quality, EncodeConfig::qualityAlpha, RGB_DEPTH, SetAvifOption(), EncodeConfig::sharpness, SVT, EncodeConfig::tileColsLog2, EncodeConfig::tileRowsLog2, EncodeConfig::tune, TUNE_PSNR, and TUNE_SSIM.
Referenced by convertImageDirect().
convertImageDirect()
emscripten::val convertImageDirect (emscripten::val jsData, int width, int height, const EncodeConfig & config)
JavaScript binding wrapper for image conversion.
Takes JavaScript Uint8Array input and returns JavaScript object with result data.
Parameters
jsData JavaScript array/TypedArray containing image data
width Desired width of the output image
height Desired height of the output image
config Encoding configuration parameters
Returns
JavaScript object containing either the encoded image buffer or error information
This function:
Converts JavaScript data to C++ vector
Detects the image type
Validates the image can be processed
Calls convert_image to perform the actual conversion
Returns JavaScript object with result
Parameters
jsData JavaScript array/TypedArray containing image data
width Desired width of the output image
height Desired height of the output image
config Encoding configuration parameters
Returns
JavaScript object containing either the encoded image buffer or error information
Definition at line 243 of file imageconverter.cpp.
References convert_image(), ImageGuru::GetImageType(), ImageGuru::isSupported(), toJsError(), ImageGuru::typeToString(), UNKNOWN, UNKNOWN_ERROR, and UNSUPPORTED_IMAGETYPE.
Referenced by EMSCRIPTEN_BINDINGS().