ConvAvif: Speed Struct Reference
Speed Struct Reference
Speed settings manager for AVIF encoding.
#include <encoder_config.h>
Public Member Functions
Speed (CodecChoice codec, SpeedPreset preset)
Constructor that sets appropriate speed ranges based on codec and preset.
int getDefault () const
Get the default speed value.
void setSpeedRange (const SpeedRange &range)
Set a new speed range.
SpeedRange getRange () const
Get the current speed range.
bool isValid (int speed)
Check if a speed value is within the valid range.
SpeedPreset getPreset () const
Get the current speed preset.
void set (int ns)
Set a new speed value if it's valid.
Public Attributes
SpeedPreset preset_ = SpeedPreset::Good
Current speed preset.
int default_speed = 5
Default speed value.
SpeedRange speed_range = {5, 6}
Valid speed range.
Detailed Description
Speed settings manager for AVIF encoding.
This class manages speed settings based on the selected codec and preset. Different codecs have different optimal speed ranges for various quality/speed tradeoffs.
Definition at line 60 of file encoder_config.h.
Constructor & Destructor Documentation
Speed()
Speed::Speed (CodecChoice codec, SpeedPreset preset) inline
Constructor that sets appropriate speed ranges based on codec and preset.
Parameters
codec The selected codec (AOM, SVT, AUTO)
preset The desired speed preset (Good, MemoryHungry, RealTime)
Definition at line 72 of file encoder_config.h.
References AOM, AUTO, default_speed, Good, MemoryHungry, preset_, RealTime, speed_range, and SVT.
Member Function Documentation
getDefault()
int Speed::getDefault () const inline
Get the default speed value.
Returns
Current default speed value
Definition at line 130 of file encoder_config.h.
References default_speed.
Referenced by EMSCRIPTEN_BINDINGS().
getPreset()
SpeedPreset Speed::getPreset () const inline
Get the current speed preset.
Returns
Current SpeedPreset value
Definition at line 157 of file encoder_config.h.
References preset_.
Referenced by EMSCRIPTEN_BINDINGS().
getRange()
SpeedRange Speed::getRange () const inline
Get the current speed range.
Returns
Current speed range
Definition at line 142 of file encoder_config.h.
References speed_range.
Referenced by EMSCRIPTEN_BINDINGS().
isValid()
bool Speed::isValid (int speed) inline
Check if a speed value is within the valid range.
Parameters
speed Speed value to check
Returns
true if speed is valid, false otherwise
Definition at line 149 of file encoder_config.h.
References speed_range.
Referenced by EMSCRIPTEN_BINDINGS(), and set().
set()
void Speed::set (int ns) inline
Set a new speed value if it's valid.
Parameters
ns New speed value to set
Definition at line 163 of file encoder_config.h.
References default_speed, and isValid().
Referenced by EMSCRIPTEN_BINDINGS().
setSpeedRange()
void Speed::setSpeedRange (const SpeedRange & range) inline
Set a new speed range.
Parameters
range New speed range to use
Definition at line 136 of file encoder_config.h.
References speed_range.
Referenced by EMSCRIPTEN_BINDINGS().
Member Data Documentation
default_speed
int Speed::default_speed = 5
Default speed value.
Definition at line 63 of file encoder_config.h.
Referenced by EMSCRIPTEN_BINDINGS(), getDefault(), set(), and Speed().
preset_
SpeedPreset Speed::preset_ = SpeedPreset::Good
Current speed preset.
Definition at line 62 of file encoder_config.h.
Referenced by EMSCRIPTEN_BINDINGS(), getPreset(), and Speed().
speed_range
SpeedRange Speed::speed_range = {5, 6}
Valid speed range.
Definition at line 64 of file encoder_config.h.
Referenced by getRange(), isValid(), setSpeedRange(), and Speed().
The documentation for this struct was generated from the following file:
include/encoder_config.h