ConvAvif: EncodeConfig Struct Reference
EncodeConfig Struct Reference
Main configuration structure for AVIF encoding.
#include <encoder_config.h>
Public Member Functions
void setQuality (int q)
Set the quality value with validation.
void setMinQuantizer (int q)
Set the minimum quantizer value with validation.
void setMaxQuantizer (int q)
Set the maximum quantizer value with validation.
void setTileRowsLog2 (int t)
Set the tile rows log2 value with validation.
void setTileColsLog2 (int t)
Set the tile columns log2 value with validation.
void setSharpness (int s)
Set the sharpness value with validation.
int getQuality () const
Get the current quality value.
int getMinQuantizer () const
Get the current minimum quantizer value.
int getMaxQuantizer () const
Get the current maximum quantizer value.
int getTileRowsLog2 () const
Get the current tile rows log2 value.
int getTileColsLog2 () const
Get the current tile columns log2 value.
int getSharpness () const
Get the current sharpness value.
int getSpeed () const
Get the current speed value.
void setPreset (SpeedPreset newPreset)
Set a new speed preset and update speed settings.
SpeedPreset getPreset () const
Get the current speed preset.
void updateSpeed (int new_speed, SpeedPreset newPreset)
Update speed settings with new values.
CodecChoice getCodecChoice () const
Get the current codec choice.
void setCodecChoice (CodecChoice choice)
Set a new codec choice and update speed settings.
void printConfig () const
Print the current configuration to stdout.
Public Attributes
int quality = 30
Quality value (0-100, higher is better quality)
int qualityAlpha = -1
Alpha channel quality (-1 means use quality value)
int sharpness = 0
Sharpness filter strength (0-7)
avifPixelFormat pixelFormat = AVIF_PIXEL_FORMAT_YUV420
YUV pixel format.
CodecChoice codecChoice
Selected codec (AOM, SVT, AUTO)
SpeedPreset preset
Speed preset.
int minQuantizer = -1
Minimum quantizer (0-63, -1 for default)
int maxQuantizer = -1
Maximum quantizer (0-63, -1 for default)
int tileRowsLog2 = 0
Log2 of tile rows (0 = 1 tile row, 1 = 2 rows, etc)
int tileColsLog2 = 0
Log2 of tile columns.
Tune tune = Tune::TUNE_DEFAULT
Encoder tuning option.
Private Member Functions
int validatedQuality (int q) const
Validate and clamp quality value to valid range.
int validatedQuantizer (int q) const
Validate and clamp quantizer value to valid range.
int validatedTileLog2 (int t) const
Validate and clamp tile log2 value to valid range.
int validatedSharpness (int s) const
Validate and clamp sharpness value to valid range.
Private Attributes
Speed speed = Speed(CodecChoice::AOM, SpeedPreset::Good)
Speed settings.
Detailed Description
Main configuration structure for AVIF encoding.
This structure contains all the parameters that control the AVIF encoding process, including quality settings, codec choice, and various encoder-specific parameters.
Definition at line 178 of file encoder_config.h.
Member Function Documentation
getCodecChoice()
CodecChoice EncodeConfig::getCodecChoice () const inline
Get the current codec choice.
Returns
Current codec choice
Definition at line 341 of file encoder_config.h.
References codecChoice.
Referenced by EMSCRIPTEN_BINDINGS().
getMaxQuantizer()
int EncodeConfig::getMaxQuantizer () const inline
Get the current maximum quantizer value.
Returns
Current maximum quantizer value
Definition at line 280 of file encoder_config.h.
References maxQuantizer.
Referenced by EMSCRIPTEN_BINDINGS().
getMinQuantizer()
int EncodeConfig::getMinQuantizer () const inline
Get the current minimum quantizer value.
Returns
Current minimum quantizer value
Definition at line 274 of file encoder_config.h.
References minQuantizer.
Referenced by EMSCRIPTEN_BINDINGS().
getPreset()
SpeedPreset EncodeConfig::getPreset () const inline
Get the current speed preset.
Returns
Current speed preset
Definition at line 319 of file encoder_config.h.
References preset.
Referenced by EMSCRIPTEN_BINDINGS().
getQuality()
int EncodeConfig::getQuality () const inline
Get the current quality value.
Returns
Current quality value
Definition at line 268 of file encoder_config.h.
References quality.
Referenced by EMSCRIPTEN_BINDINGS().
getSharpness()
int EncodeConfig::getSharpness () const inline
Get the current sharpness value.
Returns
Current sharpness value
Definition at line 298 of file encoder_config.h.
References sharpness.
getSpeed()
int EncodeConfig::getSpeed () const inline
Get the current speed value.
Returns
Current speed value
Definition at line 304 of file encoder_config.h.
References speed.
Referenced by convert_image(), and EMSCRIPTEN_BINDINGS().
getTileColsLog2()
int EncodeConfig::getTileColsLog2 () const inline
Get the current tile columns log2 value.
Returns
Current tile columns log2 value
Definition at line 292 of file encoder_config.h.
References tileColsLog2.
Referenced by EMSCRIPTEN_BINDINGS().
getTileRowsLog2()
int EncodeConfig::getTileRowsLog2 () const inline
Get the current tile rows log2 value.
Returns
Current tile rows log2 value
Definition at line 286 of file encoder_config.h.
References tileRowsLog2.
Referenced by EMSCRIPTEN_BINDINGS().
printConfig()
void EncodeConfig::printConfig () const inline
Print the current configuration to stdout.
Useful for debugging and logging purposes
Definition at line 357 of file encoder_config.h.
References codecChoice, maxQuantizer, minQuantizer, pixelFormat, preset, quality, qualityAlpha, sharpness, speed, tileColsLog2, tileRowsLog2, and tune.
Referenced by convert_image().
setCodecChoice()
void EncodeConfig::setCodecChoice (CodecChoice choice) inline
Set a new codec choice and update speed settings.
Parameters
choice New codec choice
Definition at line 347 of file encoder_config.h.
References codecChoice, preset, and speed.
Referenced by EMSCRIPTEN_BINDINGS().
setMaxQuantizer()
void EncodeConfig::setMaxQuantizer (int q) inline
Set the maximum quantizer value with validation.
Parameters
q New maximum quantizer value
Definition at line 244 of file encoder_config.h.
References maxQuantizer, and validatedQuantizer().
Referenced by EMSCRIPTEN_BINDINGS().
setMinQuantizer()
void EncodeConfig::setMinQuantizer (int q) inline
Set the minimum quantizer value with validation.
Parameters
q New minimum quantizer value
Definition at line 238 of file encoder_config.h.
References minQuantizer, and validatedQuantizer().
Referenced by EMSCRIPTEN_BINDINGS().
setPreset()
void EncodeConfig::setPreset (SpeedPreset newPreset) inline
Set a new speed preset and update speed settings.
Parameters
newPreset New speed preset
Definition at line 310 of file encoder_config.h.
References codecChoice, preset, and speed.
Referenced by EMSCRIPTEN_BINDINGS(), and updateSpeed().
setQuality()
void EncodeConfig::setQuality (int q) inline
Set the quality value with validation.
Parameters
q New quality value
Definition at line 232 of file encoder_config.h.
References quality, and validatedQuality().
Referenced by EMSCRIPTEN_BINDINGS().
setSharpness()
void EncodeConfig::setSharpness (int s) inline
Set the sharpness value with validation.
Parameters
s New sharpness value
Definition at line 262 of file encoder_config.h.
References sharpness, and validatedSharpness().
setTileColsLog2()
void EncodeConfig::setTileColsLog2 (int t) inline
Set the tile columns log2 value with validation.
Parameters
t New tile columns log2 value
Definition at line 256 of file encoder_config.h.
References tileColsLog2, and validatedTileLog2().
Referenced by EMSCRIPTEN_BINDINGS().
setTileRowsLog2()
void EncodeConfig::setTileRowsLog2 (int t) inline
Set the tile rows log2 value with validation.
Parameters
t New tile rows log2 value
Definition at line 250 of file encoder_config.h.
References tileRowsLog2, and validatedTileLog2().
Referenced by EMSCRIPTEN_BINDINGS().
updateSpeed()
void EncodeConfig::updateSpeed (int new_speed, SpeedPreset newPreset) inline
Update speed settings with new values.
Parameters
new_speed New speed value
newPreset New speed preset
Definition at line 327 of file encoder_config.h.
References codecChoice, setPreset(), and speed.
Referenced by EMSCRIPTEN_BINDINGS().
validatedQuality()
int EncodeConfig::validatedQuality (int q) const inline private
Validate and clamp quality value to valid range.
Parameters
q Quality value to validate
Returns
Clamped quality value
Definition at line 185 of file encoder_config.h.
References MAX_QUALITY.
Referenced by setQuality().
validatedQuantizer()
int EncodeConfig::validatedQuantizer (int q) const inline private
Validate and clamp quantizer value to valid range.
Parameters
q Quantizer value to validate
Returns
Clamped quantizer value or -1 if default value is specified
Definition at line 192 of file encoder_config.h.
References MAX_QUANTIZER.
Referenced by setMaxQuantizer(), and setMinQuantizer().
validatedSharpness()
int EncodeConfig::validatedSharpness (int s) const inline private
Validate and clamp sharpness value to valid range.
Parameters
s Sharpness value to validate
Returns
Clamped sharpness value
Definition at line 208 of file encoder_config.h.
References MAX_SHARPNESS.
Referenced by setSharpness().
validatedTileLog2()
int EncodeConfig::validatedTileLog2 (int t) const inline private
Validate and clamp tile log2 value to valid range.
Parameters
t Tile log2 value to validate
Returns
Clamped tile log2 value
Definition at line 201 of file encoder_config.h.
References MAX_TILE_LOG2.
Referenced by setTileColsLog2(), and setTileRowsLog2().
Member Data Documentation
codecChoice
CodecChoice EncodeConfig::codecChoice
Selected codec (AOM, SVT, AUTO)
Definition at line 218 of file encoder_config.h.
Referenced by convert_image(), getCodecChoice(), printConfig(), setCodecChoice(), setPreset(), and updateSpeed().
maxQuantizer
int EncodeConfig::maxQuantizer = -1
Maximum quantizer (0-63, -1 for default)
Definition at line 222 of file encoder_config.h.
Referenced by convert_image(), getMaxQuantizer(), printConfig(), and setMaxQuantizer().
minQuantizer
int EncodeConfig::minQuantizer = -1
Minimum quantizer (0-63, -1 for default)
Definition at line 221 of file encoder_config.h.
Referenced by convert_image(), getMinQuantizer(), printConfig(), and setMinQuantizer().
pixelFormat
avifPixelFormat EncodeConfig::pixelFormat = AVIF_PIXEL_FORMAT_YUV420
YUV pixel format.
Definition at line 217 of file encoder_config.h.
Referenced by convert_image(), EMSCRIPTEN_BINDINGS(), and printConfig().
preset
SpeedPreset EncodeConfig::preset
Speed preset.
Definition at line 219 of file encoder_config.h.
Referenced by getPreset(), printConfig(), setCodecChoice(), and setPreset().
quality
int EncodeConfig::quality = 30
Quality value (0-100, higher is better quality)
Definition at line 213 of file encoder_config.h.
Referenced by convert_image(), getQuality(), printConfig(), and setQuality().
qualityAlpha
int EncodeConfig::qualityAlpha = -1
Alpha channel quality (-1 means use quality value)
Definition at line 214 of file encoder_config.h.
Referenced by convert_image(), and printConfig().
sharpness
int EncodeConfig::sharpness = 0
Sharpness filter strength (0-7)
Definition at line 216 of file encoder_config.h.
Referenced by convert_image(), EMSCRIPTEN_BINDINGS(), getSharpness(), printConfig(), and setSharpness().
speed
Speed EncodeConfig::speed = Speed(CodecChoice::AOM, SpeedPreset::Good) private
Speed settings.
Definition at line 376 of file encoder_config.h.
Referenced by getSpeed(), printConfig(), setCodecChoice(), setPreset(), and updateSpeed().
tileColsLog2
int EncodeConfig::tileColsLog2 = 0
Log2 of tile columns.
Definition at line 224 of file encoder_config.h.
Referenced by convert_image(), getTileColsLog2(), printConfig(), and setTileColsLog2().
tileRowsLog2
int EncodeConfig::tileRowsLog2 = 0
Log2 of tile rows (0 = 1 tile row, 1 = 2 rows, etc)
Definition at line 223 of file encoder_config.h.
Referenced by convert_image(), getTileRowsLog2(), printConfig(), and setTileRowsLog2().
tune
Tune EncodeConfig::tune = Tune::TUNE_DEFAULT
Encoder tuning option.
Definition at line 226 of file encoder_config.h.
Referenced by convert_image(), EMSCRIPTEN_BINDINGS(), and printConfig().
The documentation for this struct was generated from the following file:
include/encoder_config.h