ConvAvif: jsResult Struct Reference
jsResult Struct Reference
JavaScript-friendly result structure.
#include <result.h>
Public Member Functions
bool hasError () const
Check if the result contains an error.
bool hasImage () const
Check if the result contains an image.
Error getError () const
Get the error from the result.
ImgaePtr getImage () const
Get the image from the result.
Public Attributes
Result result
The wrapped Result variant.
Detailed Description
JavaScript-friendly result structure.
This structure wraps the C++ Result variant and provides helper methods for JavaScript bindings to easily check result status and extract data.
Definition at line 41 of file result.h.
Member Function Documentation
getError()
Error jsResult::getError () const inline
Get the error from the result.
Returns
The Error object
Precondition
The result must contain an error (check with hasError() first)
Definition at line 61 of file result.h.
References result.
Referenced by EMSCRIPTEN_BINDINGS().
getImage()
ImgaePtr jsResult::getImage () const inline
Get the image from the result.
Returns
The image buffer pointer
Precondition
The result must contain an image (check with hasImage() first)
Definition at line 68 of file result.h.
References result.
Referenced by EMSCRIPTEN_BINDINGS().
hasError()
bool jsResult::hasError () const inline
Check if the result contains an error.
Returns
true if the result is an error, false otherwise
Definition at line 48 of file result.h.
References result.
Referenced by EMSCRIPTEN_BINDINGS().
hasImage()
bool jsResult::hasImage () const inline
Check if the result contains an image.
Returns
true if the result is an image, false otherwise
Definition at line 54 of file result.h.
References result.
Referenced by EMSCRIPTEN_BINDINGS().
Member Data Documentation
result
Result jsResult::result
The wrapped Result variant.
Definition at line 42 of file result.h.
Referenced by getError(), getImage(), hasError(), and hasImage().
The documentation for this struct was generated from the following file:
include/result.h